collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:18.037521'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 102146
- 102148
- 102150
- 102160
- 102162
- 102164
- 102174
- 102176
- 102178
- 102188
- 102190
- 102192
- 102194
- 102196
- 102206
