collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:20.572431'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 108684
- 108686
- 108688
- 108690
- 108692
- 108694
- 108696
- 110386
- 110388
- 110390
- 110392
- 110394
- 110396
- 110398
- 110400
