collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:18.856743'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 113178
- 113180
- 113476
- 113478
- 113480
- 113482
- 113484
- 113486
- 114500
- 114502
- 114504
- 114506
- 114508
- 114510
- 114512
