collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:28:19.240697'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 23690
- 23692
- 23694
- 23704
- 23706
- 23716
- 23718
- 28354
- 28356
- 28358
- 28360
- 28362
- 28364
- 28366
- 28368
