collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:21.786723'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 113144
- 113146
- 113148
- 113150
- 113152
- 113156
- 113158
- 113160
- 113162
- 113164
- 113166
- 113168
- 113170
- 113174
- 113176
