collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:28:48.342439'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 93748
- 93758
- 93768
- 93772
- 93774
- 93776
- 93786
- 93788
- 93790
- 93800
- 93802
- 93804
- 93814
- 93816
- 93820
