collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:28:49.734044'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 95094
- 95096
- 95098
- 95100
- 95102
- 95148
- 95158
- 95168
- 95178
- 95788
- 95790
- 95792
- 95802
- 95804
- 95806
