collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:24.696078'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 108198
- 108200
- 108202
- 108204
- 108206
- 108208
- 108210
- 108212
- 108214
- 108216
- 108218
- 108222
- 108224
- 108226
- 108228
