collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:30.690351'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 97582
- 97594
- 97596
- 97598
- 97608
- 97610
- 97612
- 97622
- 97624
- 97626
- 97636
- 97638
- 100750
- 100752
- 100762
