collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:28:47.564916'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 68332
- 89758
- 89760
- 89762
- 89764
- 89766
- 89768
- 89770
- 89772
- 89776
- 89778
- 89780
- 89782
- 89784
- 89786
