collection: u/rbonnetguerrini/injected_step6
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: true
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/rc2_norm
repo: /sps/lsst/users/bsanchez/hsc_processing/pgrc2subset_2/butler.yaml
run_info:
  finished: '2025-07-28T18:50:12.540936'
  started: '2025-07-24T14:01:00'
  status: completed
visits:
- 22632
- 22662
- 23694
- 23704
- 23706
- 23718
- 29336
- 29350
- 30482
- 30490
