collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:18.649716'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 106342
- 106344
- 106354
- 106356
- 106512
- 106522
- 106532
- 106542
- 106552
- 106708
- 106710
- 106712
- 106714
- 106716
- 107872
