collection: u/rbonnetguerrini/injected_step6
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: true
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/rc2_norm
repo: /sps/lsst/users/bsanchez/hsc_processing/pgrc2subset_2/butler.yaml
run_info:
  finished: '2025-07-28T18:51:29.785743'
  started: '2025-07-24T14:01:00'
  status: completed
visits:
- 11704
- 11710
- 11724
- 11738
- 11740
- 17900
- 17904
- 17906
- 17926
- 17948
- 17950
- 19680
- 19684
- 19694
- 19696
