collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:22.643959'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 103792
- 103794
- 103804
- 103806
- 103816
- 104166
- 104168
- 104170
- 104180
- 104182
- 104184
- 104484
- 104486
- 104488
- 104498
