collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:23.140229'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 111418
- 111420
- 111422
- 111424
- 111426
- 111428
- 111430
- 111432
- 111434
- 111436
- 111438
- 111440
- 113138
- 113140
- 113142
