collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:22.144120'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 105586
- 105588
- 105734
- 105736
- 105738
- 105748
- 105750
- 105752
- 105762
- 105764
- 105766
- 105776
- 105778
- 106058
- 106068
