collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:21.449556'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 101826
- 101836
- 101846
- 101856
- 102098
- 102100
- 102102
- 102112
- 102114
- 102116
- 102126
- 102128
- 102130
- 102140
- 102142
