collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:19.751620'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 106078
- 106130
- 106142
- 106144
- 106146
- 106156
- 106158
- 106160
- 106170
- 106172
- 106174
- 106184
- 106186
- 106330
- 106332
