collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:22.008246'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 104500
- 104502
- 104512
- 104514
- 104516
- 104526
- 104528
- 104582
- 104584
- 104594
- 104596
- 104606
- 104608
- 104618
- 104620
