collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:21.820443'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 100764
- 100774
- 100776
- 100786
- 100788
- 100800
- 100802
- 100804
- 100814
- 100816
- 100818
- 100820
- 100822
- 100824
- 100826
