collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:17.520301'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 103144
- 103154
- 103164
- 103166
- 103660
- 103662
- 103672
- 103674
- 103684
- 103686
- 103696
- 103698
- 103700
- 103702
- 103712
