collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:21.519080'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 102208
- 102210
- 102220
- 102222
- 102224
- 102234
- 102236
- 102410
- 102412
- 102414
- 102424
- 102426
- 102428
- 102438
- 102440
