collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:28:59.958575'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 53742
- 53744
- 53746
- 53748
- 53750
- 53752
- 53754
- 54086
- 54088
- 54090
- 54092
- 54094
- 54096
- 54098
- 54100
