collection: u/rbonnetguerrini/injected_step6
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: true
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/rc2_norm
repo: /sps/lsst/users/bsanchez/hsc_processing/pgrc2subset_2/butler.yaml
run_info:
  finished: '2025-07-28T18:51:10.690433'
  started: '2025-07-24T14:01:00'
  status: completed
visits:
- 322
- 346
- 358
- 1178
- 1184
- 1204
- 1206
- 1214
- 1220
- 1242
- 1248
- 11690
- 11694
- 11696
- 11698
