collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:29:22.140920'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 107882
- 107892
- 107902
- 107968
- 107970
- 107972
- 107974
- 107976
- 107978
- 107980
- 107982
- 107984
- 107986
- 107988
- 108196
