collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: false
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/UDEEP_norm
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-08-14T17:27:47.854821'
  started: '2025-07-24T14:01:00'
  status: running
visits:
- 17930
- 17932
- 17934
- 17944
- 17946
- 17948
- 17950
- 17952
- 17962
- 19656
- 19658
- 19660
- 19662
- 19680
- 19682
