repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
collection: run/ssp_ud_cosmos/step5_new
injection: false
cutout:
  size: 30
  coadd_science: false
  save: true
  save_features_only: true
  return_data: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/data/UDEEP_norm
lightcurves:
  patches: []
  cache_size: 5
run_info:
  status: completed
  started: '2025-07-24T14:01:00'
  finished: '2025-08-14T16:23:55.829301'
