# Ensemble training configuration with optimized hyperparameters
data:
  path: "/sps/lsst/groups/transients/HSC/fouchez/raphael/data/rc2_norm"
  visits: null
  test_size: 0.2
  val_size: 0.1

training:
  trainer_type: "ensemble"
  epochs: 1500
  learning_rate: 0.001
  batch_size: 256                       # Optimized from Bayesian search
  num_iter_per_epoch: 400
  epoch_decay_start: 80
  num_workers: 4
  output_dir: "/sps/lsst/groups/transients/HSC/fouchez/raphael/training/ensemble_50"
  num_models: 50                      
  
  use_tensorboard: true
  tensorboard_log_dir: "runs"
  experiment_name: "ensemble_50"
  log_interval: 100
  
  early_stopping:
    enabled: true
    monitor: "fnr"                      # Monitor False Negative Rate instead of loss
    mode: "min"                         # Want to minimize FNR
    patience: 80
    min_delta: 0.001   
    
  bayes_search:
    enabled: false
    
  model_params:
    input_shape: [30, 30, 1]
    num_classes: 2
    num_conv_blocks: 3                  # Optimized: 3 conv blocks
    filters_1: 48                       # Optimized
    filters_2: 96                       # Optimized
    filters_3: 96                       # Optimized  
    filters_4: 512                      # Optimized
    dropout_1: 0.34                     # Optimized: 0.3448561253302592
    dropout_2: 0.25                     # Keep default
    dropout_3: 0.37                     # Optimized: 0.3733545404663609
    units: 256                          # Optimized
random_state: 42
